# SPDX-License-Identifier: Apache-2.0
version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    assignees:
      - "swirlds-automation"
    labels:
      - "dependencies"
    cooldown:
      default-days: 5
    open-pull-requests-limit: 10

  - package-ecosystem: docker
    directory: /auth-layer-proxy
    assignees:
      - "swirlds-automation"
    labels:
      - "dependencies"
    cooldown:
      default-days: 5
    schedule:
      interval: daily

  - package-ecosystem: gradle
    directory: /hiero-dependency-versions
    assignees:
      - "swirlds-automation"
    labels:
      - "dependencies"
    cooldown:
      default-days: 5
    schedule:
      interval: weekly

  - package-ecosystem: gradle
    directory: /
    assignees:
      - "swirlds-automation"
    labels:
      - "dependencies"
    cooldown:
      default-days: 5
    schedule:
      interval: weekly
