codecov:
  max_report_age: off

# Only comment on PRs initially and when coverage changes
comment:
  layout: "diff, flags, files"
  behavior: new # deletes old comment and posts a new one
  require_changes: true

coverage:
  status:
    patch:
      default:
        target: 80%
        threshold: 1%
        only_pulls: true
    project:
      default:
        target: 80%
        threshold: 1%
        branches:
          - main

ignore:
  - "block-node/server/src/main/java/org/hiero/block/server/Server.java"
  - "block-node/base/src/main/java/org/hiero/block/server/mediator/NoOpLiveStreamMediator.java"
  - "block-node/base/src/main/java/org/hiero/block/server/producer/NoOpProducerObserver.java"
  - "block-node/base/src/main/java/org/hiero/block/server/persistence/storage/write/NoOpBlockWriter.java"
  - "simulator/src/main/java/org/hiero/block/simulator/BlockStreamSimulator.java"
  - "suites/**"
  - "tools/**"
