#!/usr/bin/env bash
# SPDX-License-Identifier: Apache-2.0
#
# WRB Distribution E2E (#3125 slice 3) — add-bn.sh
#
# Adds a single Block Node to an already-deployed Solo network POST-hoc, using
# the same `solo block node add` invocation shape as deploy_block_nodes in
# solo-deploy-network.sh. This lets the test bring up CN+MN (with MinIO) first,
# run the wrb-cli slice-1+2 flow, then layer BN1/BN2/BN3 in — matching the
# operational order of issue #3125 (BNs added after wrb-cli is producing).
#
# Usage:
#     add-bn.sh <bn-index>
#
# Reads (with the harness's own defaults as fallback):
#   DEPLOYMENT        (default "deployment-solo")
#   NAMESPACE         (default "solo-network")
#   CLUSTER_REFERENCE (default "kind-solo-cluster")
#   TOPOLOGY          (used to locate overrides/${TOPOLOGY}/bn-emb-values.yaml)
#   BN_VERSION        (optional — passed through as --chart-version if set)
#
# Overlays applied (mirrors deploy_block_nodes for consistency):
#   * overrides/bn-memory.yaml               — global BN memory sizing
#   * A synthesized chart-values file with the per-BN earliestManagedBlock read
#     from overrides/${TOPOLOGY}/bn-emb-values.yaml (embs.<index>). One source
#     of truth per topology instead of one file per BN.
#
# Assertions on success:
#   * `solo block node add` exit code is 0
#   * The block-node-<i>-0 pod exists and is Ready within `BN_READY_TIMEOUT` seconds

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SOLO_E2E_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"

: "${DEPLOYMENT:=deployment-solo}"
: "${NAMESPACE:=solo-network}"
: "${CLUSTER_REFERENCE:=kind-solo-cluster}"
: "${TOPOLOGY:=wrb-distribution-step345}"
BN_READY_TIMEOUT="${BN_READY_TIMEOUT:-300}"

bn_index="${1:?add-bn.sh: BN index required (1|2|3)}"

log() { echo "[wrb-dist-add-bn] $*"; }
fail() { echo "[wrb-dist-add-bn] ERROR: $*" >&2; exit 1; }

bn_name="block-node-${bn_index}"
memory_overlay="${SOLO_E2E_ROOT}/overrides/bn-memory.yaml"
emb_map_file="${SOLO_E2E_ROOT}/overrides/${TOPOLOGY}/bn-emb-values.yaml"

overlay_args=""
if [[ -f "${memory_overlay}" ]]; then
    overlay_args="${overlay_args} -f ${memory_overlay}"
    log "  Applying BN memory override"
else
    log "  (skipping BN memory override — file not present)"
fi

if [[ ! -f "${emb_map_file}" ]]; then
    fail "EMB map file not found: ${emb_map_file#${SOLO_E2E_ROOT}/}"
fi
bn_emb=$(yq ".embs.\"${bn_index}\"" "${emb_map_file}")
if [[ -z "${bn_emb}" || "${bn_emb}" == "null" ]]; then
    fail "No EMB value for BN index ${bn_index} in ${emb_map_file#${SOLO_E2E_ROOT}/}"
fi
synth_overlay="${TMPDIR:-/tmp}/wrb-dist-bn-${bn_index}-values.yaml"
cat > "${synth_overlay}" <<EOF
# Generated by add-bn.sh from overrides/${TOPOLOGY}/bn-emb-values.yaml.embs."${bn_index}"
blockNode:
  config:
    BLOCK_NODE_EARLIEST_MANAGED_BLOCK: "${bn_emb}"
EOF
overlay_args="${overlay_args} -f ${synth_overlay}"
log "  Applying BN${bn_index} EMB=${bn_emb} (from ${emb_map_file#${SOLO_E2E_ROOT}/})"

chart_args=""
if [[ -n "${BN_VERSION:-}" ]]; then
    # Solo's --chart-version requires a real semver-like tag (it runs the value through
    # SemanticVersion.getValidSemanticVersion, which throws on anything else) -- resolve
    # keywords like 'main'/'rc'/'latest' to an actual published tag first, the same way
    # cn-upgrade-tss.sh resolves CN_UPGRADE_VERSION, instead of passing them through as-is
    # and letting `solo block node add` fail with "Invalid block node chart version".
    resolved_bn_version="${BN_VERSION}"
    if [[ "${BN_VERSION}" == "main" || "${BN_VERSION}" == "rc" || "${BN_VERSION}" == "latest" ]]; then
        RESOLVE_SCRIPT="${SOLO_E2E_ROOT}/scripts/resolve-versions.sh"
        [[ -x "${RESOLVE_SCRIPT}" ]] || fail "resolve-versions.sh not found at ${RESOLVE_SCRIPT}"
        resolved_bn_version=$("${RESOLVE_SCRIPT}" v0.1.0 v0.1.0 "${BN_VERSION}" v0.1.0 v0.1.0 2>/dev/null \
            | grep '^bn_version=' | cut -d= -f2)
        [[ -n "${resolved_bn_version}" ]] || fail "Could not resolve BN_VERSION keyword '${BN_VERSION}'"
        log "Resolved BN_VERSION '${BN_VERSION}' -> ${resolved_bn_version}"
    fi
    chart_args="--chart-version ${resolved_bn_version}"
fi

log "Adding ${bn_name} to deployment=${DEPLOYMENT} cluster-ref=${CLUSTER_REFERENCE}..."
# shellcheck disable=SC2086
solo block node add \
    --deployment "${DEPLOYMENT}" \
    --cluster-ref "${CLUSTER_REFERENCE}" \
    ${chart_args} \
    ${overlay_args} \
    || fail "solo block node add failed for ${bn_name}"

log "Waiting for ${bn_name}-0 pod Ready (timeout ${BN_READY_TIMEOUT}s)..."
kubectl --context "${CLUSTER_REFERENCE}" --namespace "${NAMESPACE}" \
    wait --for=condition=Ready pod/"${bn_name}-0" --timeout="${BN_READY_TIMEOUT}s" \
    || {
        kubectl --context "${CLUSTER_REFERENCE}" --namespace "${NAMESPACE}" \
            describe pod/"${bn_name}-0" | tail -30 || true
        fail "${bn_name}-0 did not become Ready within ${BN_READY_TIMEOUT}s"
    }

# Match the port-forward layout that solo-port-forward.sh sets up at deploy time
# (see scripts/solo-port-forward.sh). Without these, the runner's no-errors
# assertion (curl http://localhost:16007+i/metrics) can't reach post-hoc BNs.
metrics_port=$((16006 + bn_index))
grpc_port=$((40839 + bn_index))

log "Establishing kubectl port-forwards for ${bn_name} (grpc :${grpc_port}, metrics :${metrics_port})..."
pf_log_dir="${TMPDIR:-/tmp}/wrb-dist-add-bn-pf"
mkdir -p "${pf_log_dir}"
# setsid isn't available on macOS (it's a util-linux tool); fall back to plain
# nohup there — the port-forwards still get backgrounded and survive the
# parent shell exiting, just without their own process group.
setsid_prefix=""
command -v setsid >/dev/null 2>&1 && setsid_prefix="setsid"
nohup ${setsid_prefix} kubectl --context "${CLUSTER_REFERENCE}" --namespace "${NAMESPACE}" \
    port-forward "svc/${bn_name}" "${grpc_port}:40840" \
    >"${pf_log_dir}/${bn_name}-grpc.log" 2>&1 </dev/null &
nohup ${setsid_prefix} kubectl --context "${CLUSTER_REFERENCE}" --namespace "${NAMESPACE}" \
    port-forward "svc/${bn_name}" "${metrics_port}:16007" \
    >"${pf_log_dir}/${bn_name}-metrics.log" 2>&1 </dev/null &
# Give kubectl a moment to establish the tunnel before add-bn.sh exits.
sleep 2

log "${bn_name}-0 is Ready."
