#!/usr/bin/env bash
# SPDX-License-Identifier: Apache-2.0
#
# WRB Distribution E2E (#3125 slice 4 — step 6) — reconfigure MN1's importer
# to pull live blocks from BN2 and BN3 while keeping the recordstream bucket
# downloader on as a records backup.
#
# We do this via `helm upgrade --reuse-values` on the mirror-1 release rather
# than `kubectl set env`. Reason: Spring Boot's SystemEnvironmentPropertySource
# cannot populate a list-type config from env vars alone. It reads the value
# but can't bind hiero.mirror.importer.block.nodes[i].host — the underlying
# YAML source has to declare the list. So we render a small overlay that
# adds the block config as YAML and let helm reconcile the mirror-1 chart.
#
# Reads:
#   NAMESPACE         (default "solo-network")
#   CLUSTER_REFERENCE (default "kind-solo-cluster")
#   BN_HOST_2         (default block-node-2.${NAMESPACE}.svc.cluster.local)
#   BN_HOST_3         (default block-node-3.${NAMESPACE}.svc.cluster.local)
#   MN_INSTANCE       (default "mirror-1")
#   READY_TIMEOUT     (default 300)

set -euo pipefail

: "${NAMESPACE:=solo-network}"
: "${CLUSTER_REFERENCE:=kind-solo-cluster}"
: "${BN_HOST_2:=block-node-2.${NAMESPACE}.svc.cluster.local}"
: "${BN_HOST_3:=block-node-3.${NAMESPACE}.svc.cluster.local}"
: "${MN_INSTANCE:=mirror-1}"
READY_TIMEOUT="${READY_TIMEOUT:-300}"

log() { echo "[wrb-dist-mn1-reconfig] $*"; }
fail() { echo "[wrb-dist-mn1-reconfig] ERROR: $*" >&2; exit 1; }

if ! helm --kube-context "${CLUSTER_REFERENCE}" --namespace "${NAMESPACE}" \
        status "${MN_INSTANCE}" >/dev/null 2>&1; then
    log "Available helm releases in ${NAMESPACE}:"
    helm --kube-context "${CLUSTER_REFERENCE}" --namespace "${NAMESPACE}" list || true
    fail "helm release '${MN_INSTANCE}' not found in namespace ${NAMESPACE}"
fi

overlay_file="${TMPDIR:-/tmp}/wrb-dist-mn1-block-overlay.yaml"
cat > "${overlay_file}" <<EOF
# Generated by reconfigure-mn1-to-bn-sources.sh (#3125 slice 4 step 6).
# Adds BN2 + BN3 as block-node sources on the existing mirror-1 release.
importer:
  config:
    hiero:
      mirror:
        importer:
          block:
            enabled: true
            sourceType: BLOCK_NODE
            nodes:
              - host: ${BN_HOST_2}
                port: 40840
              - host: ${BN_HOST_3}
                port: 40840
            verification:
              enabled: false
EOF

log "Rendered mirror-1 overlay: ${overlay_file}"
log "Contents:"
sed 's/^/    /' "${overlay_file}"

log "Running: helm upgrade --reuse-values ${MN_INSTANCE} ..."
mn1_chart=$(helm --kube-context "${CLUSTER_REFERENCE}" --namespace "${NAMESPACE}" \
    list -o json 2>/dev/null \
    | jq -r --arg n "${MN_INSTANCE}" '.[] | select(.name == $n) | .chart' \
    || true)

if [[ -z "${mn1_chart}" ]]; then
    fail "could not resolve chart for release ${MN_INSTANCE}"
fi
log "  Chart name/version: ${mn1_chart}"

chart_ver="${mn1_chart##*-}"
cache_dir="${HOME}/.solo/cache/charts"
chart_tgz="${cache_dir}/hedera-mirror-${chart_ver}.tgz"
if [[ ! -f "${chart_tgz}" ]]; then
    chart_tgz=$(ls -t "${cache_dir}"/*mirror*"${chart_ver}"*.tgz 2>/dev/null | head -1 || true)
fi

if [[ -z "${chart_tgz}" || ! -f "${chart_tgz}" ]]; then
    log "No cached chart for ${mn1_chart}; falling back to OCI upgrade"
    helm --kube-context "${CLUSTER_REFERENCE}" --namespace "${NAMESPACE}" \
        upgrade --reuse-values --wait --timeout "${READY_TIMEOUT}s" \
        -f "${overlay_file}" \
        "${MN_INSTANCE}" \
        oci://gcr.io/mirrornode/hedera-mirror \
        --version "${chart_ver}" \
        || fail "helm upgrade failed"
else
    log "  Using cached chart: ${chart_tgz}"
    helm --kube-context "${CLUSTER_REFERENCE}" --namespace "${NAMESPACE}" \
        upgrade --reuse-values --wait --timeout "${READY_TIMEOUT}s" \
        -f "${overlay_file}" \
        "${MN_INSTANCE}" "${chart_tgz}" \
        || fail "helm upgrade failed"
fi

log "Waiting for mirror-1 importer rollout..."
importer_deploy=$(kubectl --context "${CLUSTER_REFERENCE}" --namespace "${NAMESPACE}" \
    get deployment -l "app.kubernetes.io/instance=${MN_INSTANCE},app.kubernetes.io/component=importer" \
    -o jsonpath='{.items[0].metadata.name}' 2>/dev/null || true)
if [[ -n "${importer_deploy}" ]]; then
    kubectl --context "${CLUSTER_REFERENCE}" --namespace "${NAMESPACE}" \
        rollout status deployment/"${importer_deploy}" --timeout="${READY_TIMEOUT}s" \
        || {
            kubectl --context "${CLUSTER_REFERENCE}" --namespace "${NAMESPACE}" \
                describe deployment/"${importer_deploy}" | tail -40 || true
            fail "importer rollout did not complete"
        }
fi

log "${MN_INSTANCE} is running with BN2 + BN3 as block-node sources."
