#!/usr/bin/env bash
# SPDX-License-Identifier: Apache-2.0
#
# WRB Distribution E2E (#3125 slice 4 — step 6) — reconfigure MN1's importer
# to pull live blocks from BN2 and BN3 while keeping the recordstream bucket
# downloader on as a records backup.
#
# Two fixes were needed after earlier iterations:
#
#   * The default GraalVM-native importer image can't reflect into
#     List<BlockNodeProperties>, so we swap in the JVM image
#     (gcr.io/mirrornode/hedera-mirror-importer) — same override the network-
#     topology generator applies for all deploy-time MN overlays.
#
#   * Env-var config can't populate a list; helm upgrade needs a chart URI we
#     don't have. So we inject our own ConfigMap with an application.yaml
#     containing the block-nodes list, then patch mirror-1's importer
#     Deployment to mount it and set SPRING_CONFIG_ADDITIONAL_LOCATION.
#
# Reads:
#   NAMESPACE         (default "solo-network")
#   CLUSTER_REFERENCE (default "kind-solo-cluster")
#   BN_HOST_2         (default block-node-2.${NAMESPACE}.svc.cluster.local)
#   BN_HOST_3         (default block-node-3.${NAMESPACE}.svc.cluster.local)
#   MN_INSTANCE       (default "mirror-1")
#   MN_VERSION        (default v0.157.1 — used for the JVM importer image tag)
#   READY_TIMEOUT     (default 300)

set -euo pipefail

: "${NAMESPACE:=solo-network}"
: "${CLUSTER_REFERENCE:=kind-solo-cluster}"
: "${BN_HOST_2:=block-node-2.${NAMESPACE}.svc.cluster.local}"
: "${BN_HOST_3:=block-node-3.${NAMESPACE}.svc.cluster.local}"
: "${MN_INSTANCE:=mirror-1}"
: "${MN_VERSION:=v0.157.1}"
READY_TIMEOUT="${READY_TIMEOUT:-300}"

log() { echo "[wrb-dist-mn1-reconfig] $*"; }
fail() { echo "[wrb-dist-mn1-reconfig] ERROR: $*" >&2; exit 1; }

# 1) Find the mirror-1 importer Deployment.
importer_deploy=$(kubectl --context "${CLUSTER_REFERENCE}" --namespace "${NAMESPACE}" \
    get deployment \
    -l "app.kubernetes.io/instance=${MN_INSTANCE},app.kubernetes.io/component=importer" \
    -o jsonpath='{.items[0].metadata.name}' 2>/dev/null || true)

if [[ -z "${importer_deploy}" ]]; then
    log "All ${MN_INSTANCE} deployments:"
    kubectl --context "${CLUSTER_REFERENCE}" --namespace "${NAMESPACE}" \
        get deployment -l "app.kubernetes.io/instance=${MN_INSTANCE}" -o wide 2>&1 | tail -20 || true
    fail "no importer Deployment found for instance=${MN_INSTANCE}"
fi
log "Found importer Deployment: ${importer_deploy}"

# 2) Create our own ConfigMap with the block-source config as application.yaml.
wrb_cm_name="wrb-mn1-block-config"
wrb_cm_dir="/app/wrb-block-config"
wrb_yaml_file="${TMPDIR:-/tmp}/wrb-mn1-block-config.yaml"

cat > "${wrb_yaml_file}" <<EOF
# Generated by reconfigure-mn1-to-bn-sources.sh (#3125 slice 4 step 6).
# Loaded by the importer via SPRING_CONFIG_ADDITIONAL_LOCATION so Spring's
# config binder can populate hiero.mirror.importer.block.nodes as a List.
hiero:
  mirror:
    importer:
      block:
        enabled: true
        sourceType: BLOCK_NODE
        nodes:
          - host: ${BN_HOST_2}
            port: 40840
          - host: ${BN_HOST_3}
            port: 40840
        verification:
          enabled: false
EOF

log "Rendered ${wrb_yaml_file}"
log "Contents:"
sed 's/^/    /' "${wrb_yaml_file}"

kubectl --context "${CLUSTER_REFERENCE}" --namespace "${NAMESPACE}" \
    create configmap "${wrb_cm_name}" \
    "--from-file=application.yaml=${wrb_yaml_file}" \
    --dry-run=client -o yaml \
    | kubectl --context "${CLUSTER_REFERENCE}" --namespace "${NAMESPACE}" apply -f - \
    || fail "failed to create/patch ${wrb_cm_name}"

# 3) Patch the Deployment: JVM image + env + volume + volumeMount.
jvm_tag="${MN_VERSION#v}"
jvm_image="gcr.io/mirrornode/hedera-mirror-importer:${jvm_tag}"

patch_file="${TMPDIR:-/tmp}/wrb-mn1-deployment-patch.yaml"
cat > "${patch_file}" <<EOF
spec:
  template:
    spec:
      containers:
      - name: importer
        image: ${jvm_image}
        env:
        - name: SPRING_CONFIG_ADDITIONAL_LOCATION
          value: "file:${wrb_cm_dir}/application.yaml"
        volumeMounts:
        - name: wrb-block-config
          mountPath: ${wrb_cm_dir}
          readOnly: true
      volumes:
      - name: wrb-block-config
        configMap:
          name: ${wrb_cm_name}
EOF

log "Patching ${importer_deploy} (JVM image + config mount)..."
kubectl --context "${CLUSTER_REFERENCE}" --namespace "${NAMESPACE}" \
    patch deployment "${importer_deploy}" \
    --patch-file "${patch_file}" \
    || fail "kubectl patch failed for ${importer_deploy}"

# 4) Wait for rollout.
kubectl --context "${CLUSTER_REFERENCE}" --namespace "${NAMESPACE}" \
    rollout status deployment/"${importer_deploy}" --timeout="${READY_TIMEOUT}s" \
    || {
        kubectl --context "${CLUSTER_REFERENCE}" --namespace "${NAMESPACE}" \
            describe deployment/"${importer_deploy}" | tail -40 || true
        kubectl --context "${CLUSTER_REFERENCE}" --namespace "${NAMESPACE}" \
            logs -l "app.kubernetes.io/instance=${MN_INSTANCE},app.kubernetes.io/component=importer" \
            --tail=80 || true
        fail "${importer_deploy} rollout did not complete"
    }

log "${MN_INSTANCE} importer is running (JVM image, BN2 + BN3 as block-node sources)."
