{
 "title": "Block-Node Server Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Errors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Mediator Errors",
     "type": "stat",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "hiero_block_node_live_block_stream_mediator_error_total",
       "legendFormat": "Block Item Errors"
      }
     ]
    },
    {
     "title": "Rate of Mediator Errors",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 18, "x": 6, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "rate( hiero_block_node_live_block_stream_mediator_error_total [$__rate_interval])",
       "legendFormat": "Mediator Errors"
      }
     ]
    },
    {
     "title": "Stream Persistence Errors",
     "type": "stat",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "hiero_block_node_stream_persistence_handler_error_total",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Rate of Stream Persistence Errors",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 18, "x": 6, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "rate(hiero_block_node_stream_persistence_handler_error_total [$__rate_interval])",
       "legendFormat": "Stream Persistence Errors"
      }
     ]
    },
    {
     "title": "Total Failed Verifications",
     "type": "stat",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 32 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "last_over_time(hiero_block_node_verification_blocks_failed_total[$__interval])",
       "legendFormat": "Total Failed Verifications"
      }
     ]
    },
    {
     "title": "Failed Verifications",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 18, "x": 6, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(hiero_block_node_verification_blocks_failed_total[$__rate_interval])",
       "legendFormat": "Total Failed Verifications"
      }
     ]
    },
    {
     "title": "Total Block Persistence Errors",
     "type": "stat",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 38 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "hiero_block_node_block_persistence_error_total",
       "legendFormat": "Block Persistence Error"
      }
     ]
    },
    {
     "title": "Block Persistence Errors",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 18, "x": 6, "y": 38 },
     "targets": [
      {
       "expr": "rate( hiero_block_node_block_persistence_error_total [$__rate_interval])",
       "legendFormat": "Block Persistence Errors"
      }
     ]
    }
   ]
  },
  {
   "title": "Live Stream",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Live Block Items Received from Producer",
     "type": "stat",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "hiero_block_node_live_block_items_received_total",
       "legendFormat": "BlockItems"
      }
     ]
    },
    {
     "title": "Rate of Live Block Items Received from Producer",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 18, "x": 6, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "rate( hiero_block_node_live_block_items_received_total [$__rate_interval])",
       "legendFormat": "BlockItems"
      }
     ]
    },
    {
     "title": "Live Block Item Counter",
     "type": "stat",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "hiero_block_node_live_block_items_total",
       "legendFormat": "BlockItems"
      }
     ]
    },
    {
     "title": "Rate of Live Block Items Received by Mediator",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 18, "x": 6, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "rate( hiero_block_node_live_block_items_total [$__rate_interval])",
       "legendFormat": "BlockItems"
      }
     ]
    },
    {
     "title": "Live Block Items Consumed Counter",
     "type": "stat",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "hiero_block_node_live_block_items_consumed_total",
       "legendFormat": "BlockItems Consumed"
      }
     ]
    },
    {
     "title": "Rate of Block Items Sent to Consumer(s)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 18, "x": 6, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "rate( hiero_block_node_live_block_items_consumed_total [$__rate_interval])",
       "legendFormat": "BlockItems"
      }
     ]
    },
    {
     "title": "Live Block Latency",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 35 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expression": "($Consumers > 2) * ($Outbound - $Inbound)",
       "type": "math"
      }
     ]
    },
    {
     "title": "Block Latency",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 18, "x": 6, "y": 35 },
     "targets": [
      {
       "expression": "($Consumers > 2) * ($Outbound - $Inbound)",
       "type": "math"
      }
     ]
    },
    {
     "title": "Mediator Remaining Capacity",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 42 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "hiero_block_node_mediator_ring_buffer_remaining_capacity",
       "legendFormat": "Mediator Remaining Capacity"
      }
     ]
    },
    {
     "title": "Mediator Ring Buffer Capacity",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 18, "x": 6, "y": 42 },
     "targets": [
      {
       "expr": "min(hiero_block_node_mediator_ring_buffer_remaining_capacity)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Notifier Remaining Capacity",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 49 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "hiero_block_node_notifier_ring_buffer_remaining_capacity",
       "legendFormat": "Notifier Remaining Capacity"
      }
     ]
    },
    {
     "title": "Notifier Ring Buffer Capacity",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 18, "x": 6, "y": 49 },
     "targets": [
      {
       "expr": "min(hiero_block_node_notifier_ring_buffer_remaining_capacity)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Producers",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 56 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "hiero_block_node_producers", "legendFormat": "Producers" }
     ]
    },
    {
     "title": "Consumers",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 56 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "hiero_block_node_consumers", "legendFormat": "Consumers" }
     ]
    }
   ]
  },
  {
   "title": "Persistence",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Block Persistence Counter",
     "type": "stat",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "hiero_block_node_blocks_persisted_total",
       "legendFormat": "Block Persistence Counter"
      }
     ]
    },
    {
     "title": "Rate of Blocks Written to the File System",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 18, "x": 6, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "wps" } },
     "targets": [
      {
       "expr": "rate(hiero_block_node_blocks_persisted_total[$__rate_interval])",
       "legendFormat": "Block Persistence Counter"
      }
     ]
    }
   ]
  },
  {
   "title": "Live Stream Responses",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "PublishStreamResponses Generated",
     "type": "stat",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 635 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "hiero_block_node_successful_pub_stream_resp_total",
       "legendFormat": "PublishStreamResponses"
      }
     ]
    },
    {
     "title": "Rate of PublishStreamResponses Generated",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 18, "x": 6, "y": 635 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "rate( hiero_block_node_successful_pub_stream_resp_total [$__rate_interval])",
       "legendFormat": "PublishStreamResponses"
      }
     ]
    },
    {
     "title": "PublishStreamResponses Sent",
     "type": "stat",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 677 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "hiero_block_node_successful_pub_stream_resp_sent_total",
       "legendFormat": "PublishStreamResponses"
      }
     ]
    },
    {
     "title": "Rate of PublishStreamResponses Sent to Producers",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 18, "x": 6, "y": 677 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "rate(hiero_block_node_successful_pub_stream_resp_sent_total[$__rate_interval])",
       "legendFormat": "PublishStreamResponses"
      }
     ]
    }
   ]
  },
  {
   "title": "Verification",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Blocks Verified",
     "type": "stat",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 636 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "last_over_time(hiero_block_node_verification_blocks_verified_total[$__interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Blocks Verified",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 18, "x": 6, "y": 636 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "last_over_time(hiero_block_node_verification_blocks_verified_total[$__interval])",
       "legendFormat": "Blocks Verified over time"
      }
     ]
    },
    {
     "title": "Avg. Verification Time per Block",
     "type": "stat",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 642 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(last_over_time(hiero_block_node_verification_block_time_total[$__interval]) / last_over_time(hiero_block_node_verification_blocks_verified_total[$__interval]) )",
       "legendFormat": "__auto"
      },
      { "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Verification Time",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 18, "x": 6, "y": 642 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "(last_over_time(hiero_block_node_verification_block_time_total[$__interval]) / last_over_time(hiero_block_node_verification_blocks_verified_total[$__interval]) )",
       "legendFormat": "Average Block Verification Time in ms"
      },
      { "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Avg. Items per Block",
     "type": "stat",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 648 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "hiero_block_node_live_block_items_received_total / hiero_block_node_verification_blocks_verified_total",
       "legendFormat": "__auto"
      },
      { "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Avg. Items per Block",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 18, "x": 6, "y": 648 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "hiero_block_node_live_block_items_received_total / hiero_block_node_verification_blocks_verified_total",
       "legendFormat": "__auto"
      },
      { "legendFormat": "__auto" }
     ]
    }
   ]
  },
  {
   "title": "Ack",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Blocks Acked",
     "type": "stat",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 613 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "last_over_time(hiero_block_node_acked_blocked_total[$__interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Blocks Acked",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 18, "x": 6, "y": 613 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "last_over_time(hiero_block_node_acked_blocked_total[$__interval])",
       "legendFormat": "Blocks Acked over time"
      }
     ]
    }
   ]
  },
  {
   "title": "Block Queries",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Single Blocks Retrieved",
     "type": "stat",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "hiero_block_node_single_blocks_retrieved_total",
       "legendFormat": "Single Blocks Retrieved"
      }
     ]
    },
    {
     "title": "Rate of Single Blocks Retrieved",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 18, "x": 6, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "rate(hiero_block_node_single_blocks_retrieved_total[$__rate_interval])",
       "legendFormat": "RPS of Single Blocks Retrieval"
      }
     ]
    },
    {
     "title": "Single Blocks Not Found",
     "type": "stat",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "hiero_block_node_single_blocks_not_found_total",
       "legendFormat": "Single Blocks Not Found"
      }
     ]
    },
    {
     "title": "Rate of Single Blocks Not Found",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 18, "x": 6, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "rate( hiero_block_node_single_blocks_not_found_total [$__rate_interval])",
       "legendFormat": "Single Blocks Not Found"
      }
     ]
    },
    {
     "title": "Stream Closed-Range Historic Blocks",
     "type": "stat",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 19 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "hiero_block_node_closed_range_historic_blocks_retrieved_total",
       "legendFormat": "Closed Range Historic Blocks"
      }
     ]
    },
    {
     "title": "Stream Closed-Range Historic Blocks",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 18, "x": 6, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "rate(hiero_block_node_closed_range_historic_blocks_retrieved_total[$__rate_interval])",
       "legendFormat": "Stream Closed-Range Historical Blocks"
      }
     ]
    }
   ]
  }
 ]
}