# SPDX-License-Identifier: Apache-2.0
# Swirlds/Hiero modules - group ID migrated from com.swirlds to com.hedera.hashgraph at 0.63+
com.swirlds.base=com.hedera.hashgraph:swirlds-base
com.swirlds.config.api=com.hedera.hashgraph:swirlds-config-api
com.swirlds.config.extensions=com.hedera.hashgraph:swirlds-config-extensions
com.swirlds.config.impl=com.hedera.hashgraph:swirlds-config-impl
com.swirlds.state.api=com.hedera.hashgraph:swirlds-state-api
com.swirlds.state.impl=com.hedera.hashgraph:swirlds-state-impl
com.swirlds.virtualmap=com.hedera.hashgraph:swirlds-virtualmap
com.swirlds.common=com.hedera.hashgraph:swirlds-common
com.swirlds.metrics.api=com.hedera.hashgraph:swirlds-metrics-api
com.swirlds.metrics.impl=com.hedera.hashgraph:swirlds-metrics-impl
com.swirlds.merkledb=com.hedera.hashgraph:swirlds-merkledb
com.swirlds.logging=com.hedera.hashgraph:swirlds-logging
org.hiero.base.concurrent=com.hedera.hashgraph:base-concurrent
org.hiero.base.crypto=com.hedera.hashgraph:base-crypto
org.hiero.base.utility=com.hedera.hashgraph:base-utility
org.hiero.consensus.model=com.hedera.hashgraph:consensus-model
org.hiero.consensus.utility=com.hedera.hashgraph:consensus-utility
org.hiero.consensus.metrics=com.hedera.hashgraph:consensus-metrics
org.hiero.consensus.concurrent=com.hedera.hashgraph:consensus-concurrent
org.hiero.consensus.reconnect=com.hedera.hashgraph:consensus-reconnect
com.goterl.lazysodium=com.goterl:lazysodium-java
com.goterl.resourceloader=com.goterl:resource-loader
com.sun.jna=net.java.dev.jna:jna
org.json=org.json:json
simpleclient=io.prometheus:simpleclient
simpleclient.common=io.prometheus:simpleclient_common
simpleclient.httpserver=io.prometheus:simpleclient_httpserver
simpleclient.tracer.common=io.prometheus:simpleclient_tracer_common
org.hyperledger.besu.nativelib.common=org.hyperledger.besu:besu-native-common
org.hyperledger.besu.nativelib.secp256k1=org.hyperledger.besu:secp256k1
org.hiero.metrics=com.hedera.hashgraph:hiero-metrics
org.hiero.metrics.openmetrics.httpserver=com.hedera.hashgraph:openmetrics-httpserver
# Jars that are not yet modules used in the 'tools' project
com.google.api.gax=com.google.api:gax
com.google.auth.oauth2=com.google.auth:google-auth-library-oauth2-http
com.google.cloud.core=com.google.cloud:google-cloud-core
com.google.cloud.storage=com.google.cloud:google-cloud-storage
com.google.cloud.nio=com.google.cloud:google-cloud-nio
com.hedera.bucky=com.hedera.bucky:bucky-client
com.hedera.cryptography.wraps=com.hedera.cryptography:hedera-cryptography-wraps
com.hedera.common.nativesupport=com.hedera.common:hedera-common-nativesupport
s3mock.testcontainers=com.adobe.testing:s3mock-testcontainers
