# SPDX-License-Identifier: Apache-2.0
apiVersion: v2
appVersion: 0.20.0-rc1
description: A Helm chart for Hiero Blockstream Simulator.
home: https://github.com/hiero-ledger/hiero-block-node
keywords:
  - blocknode
  - dlt
  - hiero
  - hedera
  - hashgraph
  - blockstream
  - simulator
maintainers:
  - name: Hiero Block Node Team
    email: blocknode@hashgraph.com
name: blockstream-simulator-chart
sources:
  - https://github.com/hiero-ledger/hiero-block-node
version: 0.20.0-rc1
