# SPDX-License-Identifier: Apache-2.0
name: Agile Task or Feature
description: Create a new task or feature
projects:
  - "hiero-ledger/9"
type: feature
body:
  - type: textarea
    id: Story-Form
    attributes:
      label: Story Form
      description: |
        As a "Persona"
        I want to "Request"
        So that "Goal"
      value: |
        As a ?
        I want to ?
        So that ?
    validations:
      required: true
  - type: textarea
    id: technical-notes
    attributes:
      label: Technical Notes
      description: Add any additional detail to describe this story.
      placeholder: |
        Technical details, notes, suggestions, etc...
    validations:
      required: true
