# SPDX-License-Identifier: Apache-2.0
name: Epic
description: Create a new Epic
projects:
  - "hiero-ledger/9"
type: "epic"
body:
  - type: textarea
    id: epic-goal
    attributes:
      label: Goal
      description: Describe the goal of this epic in one or two sentences
      placeholder: |
        Make the block node spectacular.
    validations:
      required: true
  - type: textarea
    id: epic-intention
    attributes:
      label: Intention
      description: Three to five sentences about what the team intends to accomplish in order to meet the epic goal.
      placeholder: |
        Three to five sentences about what the team intends to accomplish in order to meet the epic goal.
    validations:
      required: true
  - type: textarea
    id: epic-considerations
    attributes:
      label: Considerations
      description: A list of considerations that affect the completion of this epic.
      placeholder: |
        A list of considerations that affect the completion of this epic.  This includes alternatives already considered before arriving at the intention above.
        - Consideration 1
           - Added details
        - Consideration 2
           - Added details
        - ...
    validations:
      required: false
  - type: textarea
    id: epic-detail
    attributes:
      label: Technical Details
      description: Add any additional detail to describe this epic.
      placeholder: |
        Technical details, notes, customer stories, etc...
    validations:
      required: false
  - type: textarea
    id: task-list
    attributes:
      label: Tasks and Features
      description: List features and tasks needed to complete this epic
      placeholder: |
        - [ ] feature 1
        - [ ] feature 2
        - [ ] task 1
        - [ ] ...
    validations:
      required: false
