# SPDX-License-Identifier: Apache-2.0
# Smallest plugin set that still boots and serves gRPC.
# No block provider at all, and no stream-publisher/stream-subscriber, so this node can never
# receive or serve a block by any path -- it exists to prove the four-plugin core starts.
plugins:
  names: "facility-messaging,block-access-service,health,server-status"
