# SPDX-License-Identifier: Apache-2.0
# Plugin profile for a local-file-historic node: the chart-default plugin set.
# Blocks arrive via stream-publisher, land in blocks-file-recent/historic, and are served
# to downstream clients via stream-subscriber and block-access-service. No cloud archiving.
plugins:
  names: "backfill,block-access-service,block-verification,blocks-file-historic,blocks-file-recent,facility-messaging,health,roster-bootstrap-rsa,roster-bootstrap-tss,server-status,stream-publisher,stream-subscriber"
