{{- /*
SPDX-License-Identifier: Apache-2.0
*/}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hiero-block-node.fullname" . }}-config
data:
  VERSION: {{ include "hiero-block-node.appVersion" .  | quote }}
{{- range $key, $value := .Values.blockNode.config }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
