{{- if and (and .Values.blockNode.backfill .Values.blockNode.backfill.sources) (gt (len .Values.blockNode.backfill.sources) 0) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hiero-block-node.fullname" . }}-block-node-sources
data:
  {{ .Values.blockNode.backfill.filename }}: |
    {
      "nodes": [
        {{- range $index, $node := .Values.blockNode.backfill.sources }}
        {{- if $index }},{{ end }}
        { "address": "{{ $node.address }}", "port": {{ $node.port }}, "priority": {{ $node.priority }} }
        {{- end }}
      ]
    }
{{- end }}
