{{- if .Values.blockNode.persistence.live.create }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "hiero-block-node.fullname" . }}-live
  labels:
    {{- include "hiero-block-node.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.blockNode.persistence.live.size }}
  {{- if .Values.blockNode.persistence.live.storageClass }}
  storageClassName: {{ .Values.blockNode.persistence.live.storageClass }}
  {{- end }}
{{- end }}
