 {{- if .Values.blockNode.persistence.logging.create }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "hiero-block-node.fullname" . }}-logging
  labels:
    {{- include "hiero-block-node.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.blockNode.persistence.logging.size }}
  {{- if .Values.blockNode.persistence.logging.storageClass }}
  storageClassName: {{ .Values.blockNode.persistence.logging.storageClass }}
  {{- end }}
{{- end }}
