{
 "title": "Block App Core",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Application State",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hiero_block_node:app_state_status"
    }
   ]
  },
  {
   "title": "Application State Over Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 19, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "hiero_block_node:app_state_status",
     "legendFormat": "Status Over Time"
    }
   ]
  },
  {
   "title": "Oldest Stored Block",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hiero_block_node:app_historical_oldest_block"
    }
   ]
  },
  {
   "title": "Oldest Block Over Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 19, "x": 5, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "hiero_block_node:app_historical_oldest_block",
     "legendFormat": "Oldest Block Over Time"
    }
   ]
  },
  {
   "title": "Newest Stored Block",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hiero_block_node:app_historical_newest_block"
    }
   ]
  },
  {
   "title": "Newest Block Over Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 19, "x": 5, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "hiero_block_node:app_historical_newest_block",
     "legendFormat": "Newest Block Over Time"
    }
   ]
  }
 ]
}