{
 "title": "Block-Provider: Files Historic",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Blocks Stored", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Blocks Stored (current)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hiero_block_node:files_historic_blocks_stored"
    }
   ]
  },
  {
   "title": "Blocks Stored Over Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "hiero_block_node:files_historic_blocks_stored"
    }
   ]
  },
  {
   "title": "Bytes Stored (current)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hiero_block_node:files_historic_total_bytes_stored"
    }
   ]
  },
  {
   "title": "Bytes Stored Over Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "hiero_block_node:files_historic_total_bytes_stored"
    }
   ]
  },
  { "title": "Blocks Written", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Blocks Written (in range)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(hiero_block_node:files_historic_blocks_written_total[$__range])"
    }
   ]
  },
  {
   "title": "Blocks Written Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(hiero_block_node:files_historic_blocks_written_total[$__rate_interval])"
    }
   ]
  },
  { "title": "Blocks Read", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Blocks Read (in range)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(hiero_block_node:files_historic_blocks_read_total[$__range])"
    }
   ]
  },
  {
   "title": "Blocks Read Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(hiero_block_node:files_historic_blocks_read_total[$__rate_interval])"
    }
   ]
  },
  { "title": "Zips Deletion Failed", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Zips Deletion Failed (in range)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(hiero_block_node:files_historic_zips_deleted_failed_total[$__range])"
    }
   ]
  },
  {
   "title": "Zips Deletion Failed Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(hiero_block_node:files_historic_zips_deleted_failed_total[$__rate_interval])"
    }
   ]
  }
 ]
}