{
 "title": "Block Verification Plugin",
 "tags": [
  "hiero-block-node",
  "verification"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Verification Time Elapsed", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Avg Verification Time",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(rate(hiero_block_node:verification_block_time_total[$__rate_interval]) / rate(hiero_block_node:verification_blocks_verified_total[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Avg Verification Time (over time)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "(rate(hiero_block_node:verification_block_time_total[$__rate_interval]) / rate(hiero_block_node:verification_blocks_verified_total[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Total Verification Time (Δ ms)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(hiero_block_node:verification_block_time_total[$__range])"
    }
   ]
  },
  {
   "title": "Verification Time (Δ over time)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "increase(hiero_block_node:verification_block_time_total[$__range])"
    }
   ]
  },
  { "title": "Rates", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Blocks Received Rate",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(hiero_block_node:verification_blocks_received_total[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Blocks Received Rate (over time)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(hiero_block_node:verification_blocks_received_total[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Blocks Verified Rate",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(hiero_block_node:verification_blocks_verified_total[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Blocks Verified Rate (over time)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(hiero_block_node:verification_blocks_verified_total[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Blocks Failed Rate",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(hiero_block_node:verification_blocks_failed_total[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Blocks Failed Rate (over time)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(hiero_block_node:verification_blocks_failed_total[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Blocks Error Rate",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(hiero_block_node:verification_blocks_error_total[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Blocks Error Rate (over time)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(hiero_block_node:verification_blocks_error_total[$__rate_interval])"
    }
   ]
  },
  { "title": "Units (Range)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "Blocks Received (Δ)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(hiero_block_node:verification_blocks_received_total[$__range])"
    }
   ]
  },
  {
   "title": "Blocks Received (Δ over time)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(hiero_block_node:verification_blocks_received_total[$__range])"
    }
   ]
  },
  {
   "title": "Blocks Verified (Δ)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(hiero_block_node:verification_blocks_verified_total[$__range])"
    }
   ]
  },
  {
   "title": "Blocks Verified (Δ over time)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(hiero_block_node:verification_blocks_verified_total[$__range])"
    }
   ]
  },
  {
   "title": "Blocks Failed (Δ)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(hiero_block_node:verification_blocks_failed_total[$__range])"
    }
   ]
  },
  {
   "title": "Blocks Failed (Δ over time)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(hiero_block_node:verification_blocks_failed_total[$__range])"
    }
   ]
  },
  {
   "title": "Blocks Error (Δ)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(hiero_block_node:verification_blocks_error_total[$__range])"
    }
   ]
  },
  {
   "title": "Blocks Error (Δ over time)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(hiero_block_node:verification_blocks_error_total[$__range])"
    }
   ]
  }
 ]
}