# SPDX-License-Identifier: Apache-2.0
# Test Properties File
files.recent.liveRootPath=build/tmp/data/liveRootPath
files.historic.rootPath=build/tmp/data/historic
metrics.exporter.openmetrics.http.enabled=false
verification.allBlocksHasherEnabled=false
cloud.storage.expanded.bucketName=bucket
cloud.storage.expanded.endpointUrl=http://fake:9000
cloud.storage.expanded.regionName=us-east-1
cloud.storage.expanded.accessKey=accessKey
cloud.storage.expanded.secretKey=secretKey
