# SPDX-License-Identifier: Apache-2.0
# Test Properties File
files.recent.liveRootPath=build/tmp/data/liveRootPath
files.historic.rootPath=build/tmp/data/historic
metrics.exporter.openmetrics.http.enabled=false
verification.allBlocksHasherEnabled=false
