// SPDX-License-Identifier: Apache-2.0
package org.hiero.block.node.verification.fixtures;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;

import com.hedera.hapi.node.base.NodeAddress;
import com.hedera.hapi.node.base.NodeAddressBook;
import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.security.PublicKey;
import java.security.cert.CertificateFactory;
import java.security.cert.X509Certificate;
import java.util.ArrayList;
import java.util.Base64;
import java.util.HexFormat;
import java.util.List;
import java.util.Map;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import org.hiero.block.node.app.fixtures.TestUtils;
import org.hiero.block.node.verification.RsaKeyDecoder;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

/// Builds the WRB integration-test `address-book.json` fixtures from their human-readable
/// sources, validates that [RsaKeyDecoder] can decode every entry, and writes the result
/// back into `block-node/app/src/testFixtures/resources/test-blocks/WRB/` whenever the
/// target directory is reachable from the working directory.
///
/// The tests always run — they exercise the regenerator and assert that the produced
/// [NodeAddressBook] is consumable by the verification path. If the run was launched
/// with the working directory matching this module's root (the Gradle default) the
/// regenerated bytes are written back; otherwise the file write is silently skipped.
///
/// To force a regeneration from a Gradle command line, run:
///
/// ```
/// ./gradlew :verification:test --tests '*WrbAddressBookFixtureGeneratorTest*' --rerun-tasks
/// ```
///
/// ## Solo source
///
/// `SOLO_4N/genesis-network.json` is the platform-side `Network` proto in JSON,
/// captured from a 4-node solo network. For each node it carries the node ID plus an X.509
/// `gossipCaCertificate`; we base64-decode the cert, extract its embedded RSA public key
/// as a `SubjectPublicKeyInfo`, hex-encode it, and store it as `rsaPubKey` on a
/// [NodeAddress]. [RsaKeyDecoder] only accepts SPKI today — see the TODO on that
/// class for the planned reconcile with `SigFileUtils`.
class WrbAddressBookFixtureGeneratorTest {

    /// Fixtures live under the `app` testFixtures resources, two directories up from this module's root.
    private static final Path WRB_FIXTURES_DIR = Path.of("../app/src/testFixtures/resources/test-blocks/WRB");

    private static final Pattern NODE_ID_PATTERN = Pattern.compile("\"nodeId\":\\s*\"(\\d+)\"");
    private static final Pattern GOSSIP_CERT_PATTERN = Pattern.compile("\"gossipCaCertificate\":\\s*\"([^\"]+)\"");

    @Test
    @DisplayName("Solo 4-node genesis-network.json → address-book.json (SPKI rsaPubKey)")
    void generateSoloAddressBook() throws Exception {
        final String json = readResourceUtf8("test-blocks/WRB/SOLO_4N/genesis-network.json");
        final NodeAddressBook book = soloNetworkJsonToAddressBook(json);

        assertEquals(4, book.nodeAddress().size(), "Solo network must contribute 4 nodes");
        final Map<Long, PublicKey> keyMap = RsaKeyDecoder.buildKeyMap(book);
        assertEquals(4, keyMap.size(), "RsaKeyDecoder must decode all 4 SPKIs in the generated book");
        for (long expectedNodeId = 0; expectedNodeId < 4; expectedNodeId++) {
            assertNotNull(keyMap.get(expectedNodeId), "Node " + expectedNodeId + " key must be present");
        }

        maybeWrite(book, "SOLO_4N/address-book.json");
    }

    private static NodeAddressBook soloNetworkJsonToAddressBook(final String json) throws Exception {
        final CertificateFactory cf = CertificateFactory.getInstance("X.509");
        final Base64.Decoder b64 = Base64.getDecoder();
        final HexFormat hex = HexFormat.of();
        final List<NodeAddress> entries = new ArrayList<>();

        // Walk every "node": { ... } block in nodeMetadata. Each block has a stable shape:
        // optional nodeId (defaults to 0 when absent — proto JSON omits default-valued ints)
        // followed by a base64-encoded gossipCaCertificate (an X.509 cert holding the RSA pubkey).
        int searchFrom = 0;
        while (true) {
            final int keyIdx = json.indexOf("\"node\"", searchFrom);
            if (keyIdx < 0) {
                break;
            }
            final int braceStart = json.indexOf('{', keyIdx);
            if (braceStart < 0) {
                break;
            }
            final int braceEnd = findMatchingBrace(json, braceStart);
            final String nodeBlock = json.substring(braceStart, braceEnd + 1);
            searchFrom = braceEnd + 1;

            // Skip the outer rosterEntry/node distinction: we only care about the "node" key whose
            // immediate contents include a "description" — both rosterEntry and node carry the cert,
            // but only the "node" object also carries description/accountId. Distinguishing isn't
            // strictly necessary (the cert value is identical) but anchoring on "node" keeps the
            // count exactly equal to the node count.
            if (!nodeBlock.contains("\"description\"")) {
                continue;
            }

            final Matcher idMatcher = NODE_ID_PATTERN.matcher(nodeBlock);
            final long nodeId = idMatcher.find() ? Long.parseLong(idMatcher.group(1)) : 0L;

            final Matcher certMatcher = GOSSIP_CERT_PATTERN.matcher(nodeBlock);
            if (!certMatcher.find()) {
                throw new IllegalStateException("No gossipCaCertificate in node block for nodeId=" + nodeId);
            }
            final byte[] certDer = b64.decode(certMatcher.group(1));
            final X509Certificate cert = (X509Certificate) cf.generateCertificate(new ByteArrayInputStream(certDer));
            final String spkiHex = hex.formatHex(cert.getPublicKey().getEncoded());

            entries.add(
                    NodeAddress.newBuilder().nodeId(nodeId).rsaPubKey(spkiHex).build());
        }

        return NodeAddressBook.newBuilder().nodeAddress(entries).build();
    }

    private static void maybeWrite(final NodeAddressBook book, final String relativePath) throws Exception {
        final Path out = WRB_FIXTURES_DIR.resolve(relativePath);
        if (!Files.isDirectory(out.getParent())) {
            // Working directory does not reach the testFixtures tree (e.g. test launched from
            // an unusual location) — skip the on-disk write but still surface the validation
            // assertions above.
            return;
        }
        Files.write(out, NodeAddressBook.JSON.toBytes(book).toByteArray());
    }

    private static InputStream openResource(final String path) throws IOException {
        final InputStream is = TestUtils.class.getModule().getResourceAsStream(path);
        assertNotNull(is, "Required test resource not found on classpath: " + path);
        return is;
    }

    private static String readResourceUtf8(final String path) throws Exception {
        try (InputStream is = openResource(path)) {
            return new String(is.readAllBytes(), StandardCharsets.UTF_8);
        }
    }

    private static int findMatchingBrace(final String s, final int openBraceIndex) {
        int depth = 0;
        boolean inString = false;
        boolean escape = false;
        for (int i = openBraceIndex; i < s.length(); i++) {
            final char c = s.charAt(i);
            if (escape) {
                escape = false;
                continue;
            }
            if (c == '\\') {
                escape = true;
                continue;
            }
            if (c == '"') {
                inString = !inString;
                continue;
            }
            if (inString) {
                continue;
            }
            if (c == '{') {
                depth++;
            } else if (c == '}') {
                depth--;
                if (depth == 0) {
                    return i;
                }
            }
        }
        throw new IllegalStateException("Unbalanced braces starting at index " + openBraceIndex);
    }
}
