{
 "title": "Block Access Service",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Rates", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Get Block Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(hiero_block_node:get_block_requests_total[$__rate_interval])",
     "legendFormat": "Requests Rate"
    }
   ]
  },
  {
   "title": "Success Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(hiero_block_node:get_block_requests_success_total[$__rate_interval])",
     "legendFormat": "Success Rate"
    }
   ]
  },
  {
   "title": "Not Available Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(hiero_block_node:get_block_requests_not_available_total[$__rate_interval])",
     "legendFormat": "Not Available Rate"
    }
   ]
  },
  {
   "title": "Not Found Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(hiero_block_node:get_block_requests_not_found_total[$__rate_interval])",
     "legendFormat": "Not Found Rate"
    }
   ]
  },
  { "title": "Units", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hiero_block_node:get_block_requests_total"
    }
   ]
  },
  {
   "title": "Successful Requests",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hiero_block_node:get_block_requests_success_total"
    }
   ]
  },
  {
   "title": "Not Available Requests",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hiero_block_node:get_block_requests_not_available_total"
    }
   ]
  },
  {
   "title": "Not Found Requests",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hiero_block_node:get_block_requests_not_found_total"
    }
   ]
  },
  { "title": "Percentages", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Success Percentage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "hiero_block_node:get_block_requests_success_total / hiero_block_node:get_block_requests_total * 100",
     "legendFormat": "Success Percentage"
    }
   ]
  },
  {
   "title": "Not Available Percentage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "hiero_block_node:get_block_requests_not_available_total / hiero_block_node:get_block_requests_total * 100",
     "legendFormat": "Not Available Percentage"
    }
   ]
  },
  {
   "title": "Not Found Percentage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "hiero_block_node:get_block_requests_not_found_total / hiero_block_node:get_block_requests_total * 100",
     "legendFormat": "Not Found Percentage"
    }
   ]
  }
 ]
}