{
 "title": "Stream Subscriber Plugin",
 "tags": [
  "hiero_block_node",
  "subscriber"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Current Open Connections",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "hiero_block_node:subscriber_open_connections"
    }
   ]
  },
  {
   "title": "Open Connections Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "hiero_block_node:subscriber_open_connections"
    }
   ]
  },
  {
   "title": "Errors over Range",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "increase(hiero_block_node:subscriber_errors_total[$__range])"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 18, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(hiero_block_node:subscriber_errors_total[$__rate_interval])"
    }
   ]
  }
 ]
}