{
 "title": "Block Verification Plugin",
 "tags": [
  "hiero-block-node",
  "verification"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Verification Time Elapsed", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Avg Verification Time",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(rate(blocknode_verification_block_time_total[$__rate_interval]) / rate(blocknode_verification_blocks_verified_total[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Avg Verification Time (over time)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "(rate(blocknode_verification_block_time_total[$__rate_interval]) / rate(blocknode_verification_blocks_verified_total[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Total Verification Time (Δ ns)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(blocknode_verification_block_time_total[$__range])"
    }
   ]
  },
  {
   "title": "Verification Time (Δ over time)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "increase(blocknode_verification_block_time_total[$__range])"
    }
   ]
  },
  { "title": "Rates", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Blocks Received Rate",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(blocknode_verification_blocks_received_total[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Blocks Received Rate (over time)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(blocknode_verification_blocks_received_total[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Blocks Verified Rate",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(blocknode_verification_blocks_verified_total[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Blocks Verified Rate (over time)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(blocknode_verification_blocks_verified_total[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Blocks Failed Rate",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(blocknode_verification_blocks_failed_total[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Blocks Failed Rate (over time)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(blocknode_verification_blocks_failed_total[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Blocks Error Rate",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(blocknode_verification_blocks_error_total[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Blocks Error Rate (over time)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(blocknode_verification_blocks_error_total[$__rate_interval])"
    }
   ]
  },
  { "title": "Units (Range)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 100 } },
  {
   "title": "Blocks Received (Δ)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(blocknode_verification_blocks_received_total[$__range])"
    }
   ]
  },
  {
   "title": "Blocks Received (Δ over time)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(blocknode_verification_blocks_received_total[$__range])"
    }
   ]
  },
  {
   "title": "Blocks Verified (Δ)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 109 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(blocknode_verification_blocks_verified_total[$__range])"
    }
   ]
  },
  {
   "title": "Blocks Verified (Δ over time)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 109 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(blocknode_verification_blocks_verified_total[$__range])"
    }
   ]
  },
  {
   "title": "Blocks Failed (Δ)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 117 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(blocknode_verification_blocks_failed_total[$__range])"
    }
   ]
  },
  {
   "title": "Blocks Failed (Δ over time)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 117 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(blocknode_verification_blocks_failed_total[$__range])"
    }
   ]
  },
  {
   "title": "Blocks Error (Δ)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 125 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(blocknode_verification_blocks_error_total[$__range])"
    }
   ]
  },
  {
   "title": "Blocks Error (Δ over time)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 125 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(blocknode_verification_blocks_error_total[$__range])"
    }
   ]
  },
  {
   "title": "Avg Hashing Time",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(rate(blocknode_hashing_block_time_total[$__rate_interval]) / rate(blocknode_verification_blocks_verified_total[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Avg Hashing Time (over time)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "(rate(blocknode_hashing_block_time_total[$__rate_interval]) / rate(blocknode_verification_blocks_verified_total[$__rate_interval]))"
    }
   ]
  },
  { "title": "RSA WRB Proof Verification", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 } },
  {
   "title": "RSA Verify Success Rate",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(blocknode_rsa_verification_success_total[$__rate_interval])"
    }
   ]
  },
  {
   "title": "RSA Verify Success Rate (over time)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(blocknode_rsa_verification_success_total[$__rate_interval])"
    }
   ]
  },
  {
   "title": "RSA Verify Failure Rate",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(blocknode_rsa_verification_failure_total[$__rate_interval])"
    }
   ]
  },
  {
   "title": "RSA Verify Failure Rate (over time)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(blocknode_rsa_verification_failure_total[$__rate_interval])"
    }
   ]
  },
  {
   "title": "RSA Roster Mismatch Rate",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(blocknode_rsa_roster_mismatch_total[$__rate_interval])"
    }
   ]
  },
  {
   "title": "RSA Roster Mismatch Rate (over time)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(blocknode_rsa_roster_mismatch_total[$__rate_interval])"
    }
   ]
  },
  { "title": "State-Proof Verification", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 83 } },
  {
   "title": "State-Proof Verify Success Rate",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(blocknode_state_proof_verification_success_total[$__rate_interval])"
    }
   ]
  },
  {
   "title": "State-Proof Verify Success Rate (over time)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(blocknode_state_proof_verification_success_total[$__rate_interval])"
    }
   ]
  },
  {
   "title": "State-Proof Verify Failure Rate",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(blocknode_state_proof_verification_failure_total[$__rate_interval])"
    }
   ]
  },
  {
   "title": "State-Proof Verify Failure Rate (over time)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(blocknode_state_proof_verification_failure_total[$__rate_interval])"
    }
   ]
  }
 ]
}