# SPDX-License-Identifier: Apache-2.0
name: "PR Checks"
on:
  push:
    branches:
      - main
      - release/*
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

defaults:
  run:
    shell: bash

env:
  GRADLE_EXEC: "ionice -c 2 -n 2 nice -n 19 ./gradlew "

permissions:
  id-token: write
  contents: read
  packages: write

jobs:
  package-protobuf-source:
    timeout-minutes: 5
    runs-on: hiero-block-node-linux-medium

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@fa2e9d605c4eeb9fcad4c99c224cee0c6c7f3594 # v2.16.0
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - name: Extract version
        id: extract_version
        run: |
          VERSION=$(cat version.txt)
          echo "VERSION=${VERSION}" >> $GITHUB_ENV

      - name: Set up JDK 25
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          distribution: "temurin"
          java-version: "25.0.2"

      - name: Produce artifact
        run: ${GRADLE_EXEC} :protobuf-sources:generateBlockNodeProtoArtifact

  compile:
    timeout-minutes: 20
    name: "Quality Checks and UTs"
    runs-on: hiero-block-node-linux-medium
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@fa2e9d605c4eeb9fcad4c99c224cee0c6c7f3594 # v2.16.0
        with:
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - name: Expand Shallow Clone for Spotless
        run: |
          if [ -f .git/shallow ]; then
            git fetch --unshallow --no-recurse-submodules
          else
            echo "Repository is not shallow, no need to unshallow."
          fi

      - name: Set up JDK 25
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          distribution: "temurin"
          java-version: "25.0.2"

      - name: Setup Node
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
- name: PandasWhoCode/initialize-github-job@a57cd6d8d768b2f3c95334bdd4fa8c21609fc651 # v1.0.5
   checkout: 'true'
   checkout-token: '${{ secrets.GITHUB_TOKEN }}'
   checkout-fetch-depth: '0'
   setup-node: 'true'
   node-version: '20.19.4'
   setup-java: 'true'
   java-version: '25.0.2'
   java-distribution: 'temurin'

      - name: Build
        id: gradle-build
        run: ${GRADLE_EXEC} clean assemble

      - name: Style Check
        id: spotless-check
        run: ${GRADLE_EXEC} qualityCheck --continue

      - name: Unit Tests
        id: unit-tests
        run: ${GRADLE_EXEC} check

      - name: Upload coverage report
        uses: codecov/codecov-action@1af58845a975a7985b0beb0cbe6fbbb71a41dbad # v5.5.3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: gradle/aggregation/build/reports/jacoco/testCodeCoverageReport/testCodeCoverageReport.xml
